### PR TITLE
i done hole assingment

### PR DESCRIPTION
**Pull request by Cleverprogramer**

### CODE REVIEW

**Comment by yaasiinaxmed** [comment]
pro copy past-ga iga daa waxyaabaha inta ugu badan anaa iga soo copy-garese dhib uma arko lkn naftada un ayaad qiyaameysaa taas lasoco

**Comment by Cleverprogramer** [comment]
pro

**Comment by Cleverprogramer** [comment]
anigu makaa copy gareeen pro

**Comment by yaasiinaxmed** [comment]
pro makaa copy-gareen wax matareeso waaba lojeda inaa sicaadi copy usoodhahde, waxwalba wee cad yihiin indha adeeg mesha maba taalo

**Pull request closed without merging**
